version: '3.7'

services:
  simple-server:
      container_name: simple-server
      image: simple-server
      restart: unless-stopped
      ports:
          - 8000:8000
      networks:
          nginx_net:

networks:
    nginx_net:
        external: true
